server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CarManagement?createDatabaseIfNotExist=true
    username: root
    password: Truong2092004a@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

jwt:
  secret: "MAOAaDeZDPe7abJfyyYmg6G4TQXTdQHNrGRFTdOr1whp6zdheS/COfx2GlDSMbXH"
  expiration: 86400000
  valid-duration: 3600 # in second
  refresh-duration : 36000

mailServer:
  host: smtp.gmail.com
  port: 587
  email: truongmessi2k4@gmail.com
  password: gzuk msgc rnia ahnq
  protocol: smtp
  isSSL: false
